set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/sudharsan/.ciel/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/sudharsan/.ciel/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/ALU"
set ::env(DESIGN_NAME) "alu_top"
set ::env(VERILOG_FILES) "/openlane/designs/ALU/src/alu4bit.v /openlane/designs/ALU/src/mod8counter.v /openlane/designs/ALU/src/alu_top.v"
set ::env(CLOCK_PORT) "clk"
set ::env(FP_SIZING) "absolute"
set ::env(DIE_AREA) "0 0 400 400"
set ::env(CORE_AREA) "20 20 380 380"
set ::env(FP_CORE_UTIL) "30"
set ::env(PL_TARGET_DENSITY) "0.45"
